### ISSUE TITLE
Getting serial number / manufacturer as non-root

### ISSUE THREAD

**Issue by nh2** [signal11/hidapi#118]
Hi,

I'm using the example code from http://www.signal11.us/oss/hidapi/. Why are serial and manufacturer always `(null)` when I don't run it as root?

I can see the serial without root with `cat /sys/bus/usb/devices/2-1.1/serial`, so I wonder why root is needed for hidapi and `lsusb` to see this.

Thanks

**Comment by kanchanasrishti** [comment]
Hi,
I am using libusb implementation of HID API and hid_get_serial_number_string() function is returning error even though the device is opened using hid_open() previously.
I need to read the serial number in order to keep track of multiple HID devices of same type from same vendor.
Any inputs in this regard would be helpful.
Thanks.
