### ISSUE TITLE
hid_write doesnt work on windows 7!

### ISSUE THREAD

**Issue by omarzedy** [signal11/hidapi#135]
I'm using Windows 7, VS 2012, so i build the library and try to connect to a device, I use hid_open it works and returns an address, but when I try to hid_write to the device it doesnt work and returns an error! I tried both version 0.7 and the master to same results. do you guys know what would cause this problem?

**Comment by diogofu** [comment]
Hi @pandemonium-  and @signal11 ,

I have the same problem with hid_write in a win 7 machine. It works fine in win 8.1 and win 10, as well as macOS. Can you remember if your problem (switch: break;) was in the microchip libraries for applications or on your own application?

thanks in advance.

**Comment by pandemonium-** [comment]
Wauuu!! It's been a while!. First, I excuse my bad english, I talk spanish but I will try explain to you. I used a pic micro (PIC18F2550) and as far as I can remember the problem was inside the deprecated C18 compiler. 

The error was this:
void main()
{
...
...
}

The solution was as follows: in the main function had to be so: 

void main(void)
{
...
...
}

You need to type "void".

I wish this can help you. Cheers!

**Comment by diogofu** [comment]
Hi @pandemonium- ,

thanks for the reply. I knew it was a long shot, unfortunatelly for me I'm using XC8 and that "void" was already there =(
but I'll keep looking for a solution, thanks again!

**Comment by diogofu** [comment]
Just an update, our problem was with the wrapper we were using, that was not sending the Report ID = 0x00. Now everything works fine =)

**Comment by signal11** [comment]
Wrappers are bad ;)
