### ISSUE TITLE
Downloads are double named e.g. hidapi-hidapi-0.8.0-rc1.tar.gz

### ISSUE THREAD

**Issue by barjac** [signal11/hidapi#209]
...as is the top level source dir after extraction.

**Comment by amullins83** [comment]
When you download the code instead of cloning the repo with `git clone`, the branch or tag name associated with download is appended to the zip file name. If you had downloaded from the `master` branch, it would have been named `hidapi-master`. It is a little redundant that the tags include the repo name, but since that's been this repo's convention for several versions, I don't imagine that will change anytime soon.

**Comment by barjac** [comment]
OK I can live with it - this happens in another project that I package so I will have to adopt the same approach with this.
Closing then.
